# Usar una imagen base de Node.js
FROM node:16-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de dependencias
COPY frontend/package.json frontend/package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código del frontend
COPY frontend/ .

# Construir la aplicación React
RUN npm run build

# Exponer el puerto en el que corre React
EXPOSE 3000

# Comando para ejecutar el servidor de React
CMD ["npm", "start"]